version: 2.1

executors:
  default:
    docker:
      - image: circleci/gcc:latest

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y libxcb1-dev libcairo2-dev
      - run:
          name: Build Project
          command: make
      - run:
          name: Run Tests
          command: |
            ./test_cairo_menu_render
            ./test_cairo_menu_animation

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
